### ISSUE TITLE
Error from zlib not caught while extracting

### ISSUE THREAD

**Issue by kfurmann** [alanhoff/node-tar.gz#16]
The callback from targz().extract() is not called when zlib throws an error. 
````javascript
TarGz.prototype.createWriteStream = function(directory) {
  var stream1 = zlib.createGunzip(this._options.zlib);
  var stream2 = tar.Extract({
    path: directory,
    strip: this._options.tar.strip || 0
  });

  this._bubble(stream2, stream1);
  stream1.pipe(stream2);

  return stream1;
};
````
I noticed that switching arguments for _bubble fixes the problem
````javascript
this._bubble(stream1, stream2);
````

Is this a proper solution? Should I make a pull request?

**Comment by alanhoff** [comment]
Actually yes, it's a logical problem. Could you send a pull with proper tests?

**Comment by alanhoff** [comment]
Thanks for the contribution!
