### ISSUE TITLE
Can't extract .gz file file (node 4.1.0)

### ISSUE THREAD

**Issue by flockonus** [alanhoff/node-tar.gz#18]
Hey guys, i've been trying to use it to unzip a file but can't get it to work and it don't show any errors. Can you give me some pointers? I've tried both programatically and the CLI.

This is the file: https://dl.dropboxusercontent.com/u/11210438/video--1442354402.log.gz

**Comment by flockonus** [comment]
I'm on node 4.1.0 btw

**Comment by flockonus** [comment]
Ohh yes.. so that seems to be the problem, just tried 0.10.40 and it works there :(

**Comment by emhagman** [comment]
+1

**Comment by alanhoff** [comment]
Will take a look. Any help is appreciated.

**Comment by alanhoff** [comment]
@flockonus `tar.gz` is meant to operate on tar compressed files, the file that you're trying to extract is a simple gzipped file, you should user `require('gzip')` directly
