### ISSUE TITLE
[Question] only write to disk once

### ISSUE THREAD

**Issue by justinhelmer** [alanhoff/node-tar.gz#24]
Hello, really great tool. We appreciate you simplifying the process of `.tar.gz`.

I have a question that you may be able to help with.

I am _very_ interested in taking advantage of the benefits of streaming, so I'm trying to avoid writing to the filesystem. However I'm still getting a hang of it.

Can you think of a way to write just a single file, based on some information about the entry? Or is this counter-intuitive to streaming, i.e. I would need to open up two pipes?

Something like this would be magical:

```js
var parse = targz().createParseStream();

parse.on('entry', function(entry) {
  if (entry.path.match(/node-tar/)) {
    // only falls here once
    entry.pipe(targz().createWriteStream('/versions'));
  }
});

request(tarballUrl, {gzip: true}).pipe(parse);
```

Clearly a phony example, but helps illustrate the point.

I appreciate your help with this.

**Comment by alanhoff** [comment]
I never tried but I think it's perfectly possible.The `entry` emitted is an stream that contains the file/folder already uncompressed, so you don't need to create another targz stream, just pipe it directly to `fs.createWriteStream()`.

Have you tried it?

**Comment by justinhelmer** [comment]
I was unable to get it to work, but I am a total newbie. For the time being, I am using `targz().createWriteStream()` and piping `request()`. It downloads the entire set of assets when I really only need one file, but it does do the trick.

**Comment by alanhoff** [comment]
Did you received any error or something I can help?

**Comment by justinhelmer** [comment]
I'm closing this issue, because I don't want to take any more of your valuable time or pollute your queue, and I am really swamped.

I will re-open when I have a few free minutes. This stuff is super interesting to me.

Thanks alot, @alanhoff . Found this tool much easier to use than everything else out there, and it's all in one stream.

Cheers.

**Comment by alanhoff** [comment]
No worries! Cheers!
