### ISSUE TITLE
Question : can it archive only one file ?

### ISSUE THREAD

**Issue by baramuse** [alanhoff/node-tar.gz#30]
Hi !

I'm trying to compress only one file, is that possible ?

When I'm trying to do it, it create the output .tar.gz, and that's it...it get stuck there, like it was waiting for an input.
I'm trying with the promise version (by the way, is there any plan to use native promises instead of bluebird ?)

`TARGZ().compress(inputFilePath, destFilePath + '.tar.gz');`

Thanks !

**Comment by alanhoff** [comment]
Hello @baramuse! So, a `.tar.gz` file is a single file created by two technologies: tar and gzip. The tar one is used as a container for packing a single file into a single one and also unpacking a compatible single file into multiple original files. The gzip is the last one and is used to compress that single packed file created by tar.

So it doesn't makes sense to try to pack a single file into a tar structure. If you want to compress a single file you can use directly `gzip` as below:

```javascript
let fs = require('fs')
let zlib = require('zlib')

let read = fs.createReadStream('my-input-file.txt')
let write = fs.createWriteStream('my-output-file.txt')
let compress = zlib.createGzip()

// Pipe everything together
read.pipe(compress).pipe(write)
```

You could also move your single file into a folder and `targz.compress('/that/folder')` but you will end up with a file a little bigger than directly compressing the single file.

Sorry for the long answer, it's for posterior reference :-)

**Comment by baramuse** [comment]
Hi @alanhoff !

thanks for the comprehensive answer!
I was suspecting it was the reason but I got mislead by the `compress()` name of the function so I though I might as well ask :)

I'll go with zlib then !

Cheers
